version: "2"

services:
    app:
        image: ebuildy/vignestore:latest
        #volumes:
        #    - .:/var/www/html
        environment:
            DATABASE_URL: "mysql://root:root@mysql:3306/vignestore?serverVersion=5.7"

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vignestore

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOSTS: mysql
        ports:
            - 8080:80